package authtemplate.infrastructure.security.configuration

import authtemplate.infrastructure.security.token.properties.TokenProperties
import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(TokenProperties::class)
class TokenConfig