name: capybara CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set environment values
        run: |
          rm -f .env 
          echo "${{ secrets.ENV }}" > .env
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/capybara:latest
          platforms: linux/amd64

      - name: ssh to gcp
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            sudo docker stop capybara-container || true
            sudo docker rm capybara-container || true

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/capybara:latest
            
            sudo docker run -d --name capybara-container --env-file .env -p 443:443 -e TZ=Asia/Seoul ${{ secrets.DOCKER_USERNAME }}/capybara:latest
